# Generated by Django 2.0 on 2019-09-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='f_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='l_name',
            new_name='lastname',
        ),
    ]
